# -*- coding: utf-8 -*-
"""DS602_stat_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaMoicTmE2bi3tnbLe25DtrgKPOlxgpz
"""


import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.stattools import jarque_bera, omni_normtest

# --- Page Config ---
st.set_page_config(page_title="Lab 4: Applied Statistical Modeling", layout="wide")
st.title("Lab-4: Applied Statistical Modeling & Interactive Web Dashboard")
st.markdown("M.Sc. Data Science — Semester 1 | Dataset: Medical Insurance Costs")

# --- Data Loading ---
@st.cache_data
def load_data():
    # Using a standard URL for the Insurance dataset (Kaggle/Medical Insurance)
    # If this fails, ensure you have 'data/insurance.csv' in your local folder
    try:
        # Try local first
        df = pd.read_csv('data/insurance.csv')
    except:
        # Fallback to URL
        url = "https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv"
        df = pd.read_csv(url)
    return df

df = load_data()

# --- Sidebar Filters ---
st.sidebar.header("Data Filters")
age_min, age_max = st.sidebar.slider("Age Range", int(df['age'].min()), int(df['age'].max()), (int(df['age'].min()), int(df['age'].max())))
sex_filter = st.sidebar.multiselect("Sex", df['sex'].unique(), default=df['sex'].unique())
smoker_filter = st.sidebar.multiselect("Smoker Status", df['smoker'].unique(), default=df['smoker'].unique())

# Filtered Data for Exploration
df_filtered = df[(df['age'].between(age_min, age_max)) &
                 (df['sex'].isin(sex_filter)) &
                 (df['smoker'].isin(smoker_filter))]

# --- Tabs ---
tab1, tab2, tab3 = st.tabs(["📊 Data Exploration", "🧪 Hypothesis Testing Lab", "🔮 Live Prediction & Diagnostics"])

# =================================
# TAB 1: DATA EXPLORATION
# =================================
with tab1:
    st.subheader("1. Exploratory Data Analysis")

    # Descriptive Stats
    st.markdown("#### Descriptive Metrics")
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Mean Charges", f"{df_filtered['charges'].mean():.2f}")
        st.metric("Median Charges", f"{df_filtered['charges'].median():.2f}")
    with col2:
        st.metric("Std Dev", f"{df_filtered['charges'].std():.2f}")
        st.metric("IQR", f"{df_filtered['charges'].quantile(0.75) - df_filtered['charges'].quantile(0.25):.2f}")
    with col3:
        st.metric("Skewness", f"{df_filtered['charges'].skew():.2f}")
        st.metric("Kurtosis", f"{df_filtered['charges'].kurtosis():.2f}")
    with col4:
        st.metric("Count", len(df_filtered))

    # Visuals
    st.markdown("#### Distribution & Correlation")
    fig1, fig2 = st.columns(2)

    with fig1:
        st.markdown("**Distribution of Medical Charges**")
        fig_dist = px.histogram(df_filtered, x='charges', nbins=50, title='Charges Distribution')
        st.plotly_chart(fig_dist, use_container_width=True)

    with fig2:
        st.markdown("**Correlation Matrix**")
        numeric_cols = ['age', 'bmi', 'children', 'charges']
        corr = df_filtered[numeric_cols].corr()
        fig_corr = px.imshow(corr, text_auto=True, title='Correlation Heatmap')
        st.plotly_chart(fig_corr, use_container_width=True)

    st.markdown("#### Bivariate Scatter: BMI vs Charges (Colored by Smoker)")
    fig_scatter = px.scatter(df_filtered, x='bmi', y='charges', color='smoker',
                             hover_data=['age', 'sex', 'region'], title='BMI vs Medical Charges')
    st.plotly_chart(fig_scatter, use_container_width=True)

# =================================
# TAB 2: HYPOTHESIS TESTING LAB
# =================================
with tab2:
    st.subheader("2. Hypothesis Testing")

    st.markdown("#### Test 1: Two-Sample Comparison (Smokers vs Non-Smokers)")
    st.markdown("H0: No difference in mean charges between smokers and non-smokers.")
    st.markdown("H1: There is a significant difference.")

    smokers = df[df['smoker'] == 'yes']['charges']
    non_smokers = df[df['smoker'] == 'no']['charges']

    # Normality Check (Shapiro-Wilk)
    stat_s, p_s_smokers = stats.shapiro(smokers)
    stat_ns, p_s_non = stats.shapiro(non_smokers)

    st.write(f"**Shapiro-Wilk Test:**")
    st.write(f"- Smokers p-value: {p_s_smokers:.4f} (Normal: {'Yes' if p_s_smokers > 0.05 else 'No'})")
    st.write(f"- Non-Smokers p-value: {p_s_non:.4f} (Normal: {'Yes' if p_s_non > 0.05 else 'No'})")

    # Levene's Test for Equal Variance
    stat_l, p_l = stats.levene(smokers, non_smokers)
    st.write(f"**Levene's Test:** p-value = {p_l:.4f} (Equal Variance: {'Yes' if p_l > 0.05 else 'No'})")

    # Choose Test
    if p_s_smokers > 0.05 and p_s_non > 0.05:
        st.write("Assuming Normality: Running **Two-Sample t-test**")
        stat_t, p_t = stats.ttest_ind(smokers, non_smokers, equal_var=(p_l > 0.05))
        test_name = "t-test"
        stat_val = stat_t
        p_val = p_t
    else:
        st.write("Non-Normal Distribution: Running **Mann-Whitney U test**")
        stat_u, p_u = stats.mannwhitneyu(smokers, non_smokers)
        test_name = "Mann-Whitney U"
        stat_val = stat_u
        p_val = p_u

    st.markdown(f"**Result ({test_name}):**")
    st.write(f"- Test Statistic: {stat_val:.4f}")
    st.write(f"- p-value: {p_val:.4f}")
    conclusion1 = "Reject H0" if p_val < 0.05 else "Fail to Reject H0"
    st.success(f"**Conclusion:** {conclusion1} at α = 0.05. There is a significant difference in charges.")

    st.markdown("---lasting")
    st.markdown("#### Test 2: One-Way ANOVA (Charges across Regions)")
    st.markdown("H0: Mean charges are equal across all regions.")
    st.markdown("H1: At least one region has a different mean charge.")

    groups = [group['charges'].values for name, group in df.groupby('region')]
    stat_f, p_f = stats.f_oneway(*groups)

    st.write(f"**ANOVA Result:**")
    st.write(f"- F-statistic: {stat_f:.4f}")
    st.write(f"- p-value: {p_f:.4f}")
    conclusion2 = "Reject H0" if p_f < 0.05 else "Fail to Reject H0"
    st.success(f"**Conclusion:** {conclusion2} at α = 0.05. Mean charges differ significantly across regions.")

# =================================
# TAB 3: LIVE PREDICTION & DIAGNOSTICS
# =================================
with tab3:
    st.subheader("3. OLS Regression & Diagnostics")

    # Prepare Data for OLS
    # We will model: charges ~ age + bmi + children + smoker (dummy)
    df_model = df.copy()
    df_model['smoker_num'] = (df_model['smoker'] == 'yes').astype(int)

    X = df_model[['age', 'bmi', 'children', 'smoker_num']]
    X = sm.add_constant(X)
    y = df_model['charges']

    # Fit OLS
    model = sm.OLS(y, X).fit()
    st.write("#### OLS Model Summary")
    st.markdown(model.summary().as_html(), unsafe_allow_html=True)

    # Diagnostics
    st.markdown("#### Gauss-Markov Diagnostic Checks")

    # 1. Residuals vs Fitted
    fig_resid = px.scatter(x=model.fittedvalues, y=model.resid,
                           title='Residuals vs Fitted Values',
                           labels={'x': 'Fitted Values', 'y': 'Residuals'})
    fig_resid.add_hline(y=0, line_dash="dash", line_color="red")
    st.plotly_chart(fig_resid, use_container_width=True)

    # 2. Normality of Residuals (Q-Q Plot)
    fig, ax = plt.subplots()
    sm.qqplot(model.resid, line='45', ax=ax)
    ax.set_title('Q-Q Plot of Residuals')
    st.pyplot(fig)

    # Jarque-Bera Test
    jb_stat, jb_p, _, _ = jarque_bera(model.resid)
    st.write(f"**Jarque-Bera Test:** Statistic = {jb_stat:.4f}, p-value = {jb_p:.4f}")
    st.write(f"Normality of Residuals: {'Assumed' if jb_p > 0.05 else 'Rejected'}")

    # 3. Multicollinearity (VIF)
    st.markdown("#### Variance Inflation Factor (VIF)")
    vif_data = pd.DataFrame()
    vif_data["Feature"] = X.columns
    vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    st.dataframe(vif_data, use_container_width=True)

    # Live Prediction
    st.markdown("---lasting")
    st.subheader("Live Prediction Tool")
    st.markdown("Enter patient details to predict medical charges:")

    col_p1, col_p2, col_p3, col_p4 = st.columns(4)
    with col_p1:
        p_age = st.slider("Age", 18, 64, 30)
    with col_p2:
        p_bmi = st.slider("BMI", 15.0, 50.0, 25.0)
    with col_p3:
        p_children = st.slider("Children", 0, 5, 0)
    with col_p4:
        p_smoker = st.selectbox("Smoker", ['No', 'Yes'])

    if st.button("Predict Charges"):
        # Create input dataframe
        input_df = pd.DataFrame({
            'const': 1,
            'age': [p_age],
            'bmi': [p_bmi],
            'children': [p_children],
            'smoker_num': [1 if p_smoker == 'Yes' else 0]
        })

        # Prediction
        prediction = model.predict(input_df)

        # Confidence Interval (Approximate for prediction interval in statsmodels OLS)
        # Note: For a true prediction interval, we need to calculate manually using standard error of prediction
        # Here we provide the point estimate and a rough CI based on model parameters
        conf_int = model.get_prediction(input_df).conf_int(alpha=0.05)
        ci_lower = conf_int[0][0]
        ci_upper = conf_int[0][1]

        st.success(f"**Predicted Medical Charges:** ${prediction[0]:,.2f}")
        st.info(f"**95% Confidence Interval:** ${ci_lower:,.2f} - ${ci_upper:,.2f}")
